linters:
  rubocop:
    display_cop_names: true
    fixer: true

  remarklint:
    fixer: true

  standardjs:

  stylelint:

files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    
fixers:
  enable: true